# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

name: $(Year:yyyy).$(Month).$(DayOfMonth).$(Rev:.r)

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './SigniFlow.Connect.sln'
    arguments: '-c Release'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './SigniFlow.Connect.sln'
    arguments: '-c Release'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: './src/SigniFlow.Connect/SigniFlow.Connect.csproj'
    versioningScheme: 'byBuildNumber'
- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.Org'