/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SigniFlow.Connect.Client.OpenAPIDateConverter;

namespace SigniFlow.Connect.Model
{
    /// <summary>
    /// #### Document Extension   &#x60; 0 &#x3D; pdf 1 &#x3D; xls 2 &#x3D; txt 3 &#x3D; xlsx 4 &#x3D; docx 5 &#x3D; doc 6 &#x3D; xml 7 &#x3D; png 8 &#x3D; jpg 9 &#x3D; gif &#x60; 
    /// </summary>
    /// <value>#### Document Extension   &#x60; 0 &#x3D; pdf 1 &#x3D; xls 2 &#x3D; txt 3 &#x3D; xlsx 4 &#x3D; docx 5 &#x3D; doc 6 &#x3D; xml 7 &#x3D; png 8 &#x3D; jpg 9 &#x3D; gif &#x60; </value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum DocExtension
    {
        /// <summary>
        /// Enum pdf for value: 0
        /// </summary>
        [EnumMember(Value = "0")]
        pdf = 1,

        /// <summary>
        /// Enum xls for value: 1
        /// </summary>
        [EnumMember(Value = "1")]
        xls = 2,

        /// <summary>
        /// Enum txt for value: 2
        /// </summary>
        [EnumMember(Value = "2")]
        txt = 3,

        /// <summary>
        /// Enum xlsx for value: 3
        /// </summary>
        [EnumMember(Value = "3")]
        xlsx = 4,

        /// <summary>
        /// Enum docx for value: 4
        /// </summary>
        [EnumMember(Value = "4")]
        docx = 5,

        /// <summary>
        /// Enum doc for value: 5
        /// </summary>
        [EnumMember(Value = "5")]
        doc = 6,

        /// <summary>
        /// Enum xml for value: 6
        /// </summary>
        [EnumMember(Value = "6")]
        xml = 7,

        /// <summary>
        /// Enum png for value: 7
        /// </summary>
        [EnumMember(Value = "7")]
        png = 8,

        /// <summary>
        /// Enum jpg for value: 8
        /// </summary>
        [EnumMember(Value = "8")]
        jpg = 9,

        /// <summary>
        /// Enum gif for value: 9
        /// </summary>
        [EnumMember(Value = "9")]
        gif = 10

    }

}
