/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SigniFlow.Connect.Client.OpenAPIDateConverter;

namespace SigniFlow.Connect.Model
{
    /// <summary>
    /// MultipleSignersSigningCeremonyRequestSignerListField
    /// </summary>
    [DataContract]
    public partial class MultipleSignersSigningCeremonyRequestSignerListField :  IEquatable<MultipleSignersSigningCeremonyRequestSignerListField>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MultipleSignersSigningCeremonyRequestSignerListField" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MultipleSignersSigningCeremonyRequestSignerListField() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MultipleSignersSigningCeremonyRequestSignerListField" /> class.
        /// </summary>
        /// <param name="signatureHField">signatureHField (required).</param>
        /// <param name="signatureImageField">signatureImageField (required).</param>
        /// <param name="signatureImageIncludeBorderField">signatureImageIncludeBorderField (required).</param>
        /// <param name="signatureImageIncludeReasonField">signatureImageIncludeReasonField (required).</param>
        /// <param name="signatureImageIncludeSignedByField">signatureImageIncludeSignedByField (required).</param>
        /// <param name="signatureImageIncludeSignedDateField">signatureImageIncludeSignedDateField (required).</param>
        /// <param name="signatureImageTypeField">signatureImageTypeField (required).</param>
        /// <param name="signaturePageField">signaturePageField (required).</param>
        /// <param name="signatureWField">signatureWField (required).</param>
        /// <param name="signatureXField">signatureXField (required).</param>
        /// <param name="signatureYField">signatureYField (required).</param>
        /// <param name="signerEmailField">signerEmailField (required).</param>
        /// <param name="signerFullNameField">signerFullNameField (required).</param>
        /// <param name="signerIndentificationNumberField">signerIndentificationNumberField (required).</param>
        /// <param name="signerLocationField">signerLocationField (required).</param>
        /// <param name="signerMobileNumberField">signerMobileNumberField (required).</param>
        /// <param name="signerReasonField">signerReasonField (required).</param>
        /// <param name="signerTrustOriginField">signerTrustOriginField (required).</param>
        /// <param name="signerTrustReferenceField">signerTrustReferenceField (required).</param>
        public MultipleSignersSigningCeremonyRequestSignerListField(decimal signatureHField = default(decimal), string signatureImageField = default(string), bool signatureImageIncludeBorderField = default(bool), bool signatureImageIncludeReasonField = default(bool), bool signatureImageIncludeSignedByField = default(bool), bool signatureImageIncludeSignedDateField = default(bool), decimal signatureImageTypeField = default(decimal), decimal signaturePageField = default(decimal), decimal signatureWField = default(decimal), decimal signatureXField = default(decimal), decimal signatureYField = default(decimal), string signerEmailField = default(string), string signerFullNameField = default(string), string signerIndentificationNumberField = default(string), string signerLocationField = default(string), string signerMobileNumberField = default(string), string signerReasonField = default(string), string signerTrustOriginField = default(string), string signerTrustReferenceField = default(string))
        {
            // to ensure "signatureHField" is required (not null)
            if (signatureHField == null)
            {
                throw new InvalidDataException("signatureHField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignatureHField = signatureHField;
            }

            // to ensure "signatureImageField" is required (not null)
            if (signatureImageField == null)
            {
                throw new InvalidDataException("signatureImageField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignatureImageField = signatureImageField;
            }

            // to ensure "signatureImageIncludeBorderField" is required (not null)
            if (signatureImageIncludeBorderField == null)
            {
                throw new InvalidDataException("signatureImageIncludeBorderField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignatureImageIncludeBorderField = signatureImageIncludeBorderField;
            }

            // to ensure "signatureImageIncludeReasonField" is required (not null)
            if (signatureImageIncludeReasonField == null)
            {
                throw new InvalidDataException("signatureImageIncludeReasonField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignatureImageIncludeReasonField = signatureImageIncludeReasonField;
            }

            // to ensure "signatureImageIncludeSignedByField" is required (not null)
            if (signatureImageIncludeSignedByField == null)
            {
                throw new InvalidDataException("signatureImageIncludeSignedByField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignatureImageIncludeSignedByField = signatureImageIncludeSignedByField;
            }

            // to ensure "signatureImageIncludeSignedDateField" is required (not null)
            if (signatureImageIncludeSignedDateField == null)
            {
                throw new InvalidDataException("signatureImageIncludeSignedDateField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignatureImageIncludeSignedDateField = signatureImageIncludeSignedDateField;
            }

            // to ensure "signatureImageTypeField" is required (not null)
            if (signatureImageTypeField == null)
            {
                throw new InvalidDataException("signatureImageTypeField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignatureImageTypeField = signatureImageTypeField;
            }

            // to ensure "signaturePageField" is required (not null)
            if (signaturePageField == null)
            {
                throw new InvalidDataException("signaturePageField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignaturePageField = signaturePageField;
            }

            // to ensure "signatureWField" is required (not null)
            if (signatureWField == null)
            {
                throw new InvalidDataException("signatureWField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignatureWField = signatureWField;
            }

            // to ensure "signatureXField" is required (not null)
            if (signatureXField == null)
            {
                throw new InvalidDataException("signatureXField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignatureXField = signatureXField;
            }

            // to ensure "signatureYField" is required (not null)
            if (signatureYField == null)
            {
                throw new InvalidDataException("signatureYField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignatureYField = signatureYField;
            }

            // to ensure "signerEmailField" is required (not null)
            if (signerEmailField == null)
            {
                throw new InvalidDataException("signerEmailField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignerEmailField = signerEmailField;
            }

            // to ensure "signerFullNameField" is required (not null)
            if (signerFullNameField == null)
            {
                throw new InvalidDataException("signerFullNameField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignerFullNameField = signerFullNameField;
            }

            // to ensure "signerIndentificationNumberField" is required (not null)
            if (signerIndentificationNumberField == null)
            {
                throw new InvalidDataException("signerIndentificationNumberField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignerIndentificationNumberField = signerIndentificationNumberField;
            }

            // to ensure "signerLocationField" is required (not null)
            if (signerLocationField == null)
            {
                throw new InvalidDataException("signerLocationField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignerLocationField = signerLocationField;
            }

            // to ensure "signerMobileNumberField" is required (not null)
            if (signerMobileNumberField == null)
            {
                throw new InvalidDataException("signerMobileNumberField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignerMobileNumberField = signerMobileNumberField;
            }

            // to ensure "signerReasonField" is required (not null)
            if (signerReasonField == null)
            {
                throw new InvalidDataException("signerReasonField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignerReasonField = signerReasonField;
            }

            // to ensure "signerTrustOriginField" is required (not null)
            if (signerTrustOriginField == null)
            {
                throw new InvalidDataException("signerTrustOriginField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignerTrustOriginField = signerTrustOriginField;
            }

            // to ensure "signerTrustReferenceField" is required (not null)
            if (signerTrustReferenceField == null)
            {
                throw new InvalidDataException("signerTrustReferenceField is a required property for MultipleSignersSigningCeremonyRequestSignerListField and cannot be null");
            }
            else
            {
                this.SignerTrustReferenceField = signerTrustReferenceField;
            }

        }

        /// <summary>
        /// Gets or Sets SignatureHField
        /// </summary>
        [DataMember(Name="SignatureHField", EmitDefaultValue=true)]
        public decimal SignatureHField { get; set; }

        /// <summary>
        /// Gets or Sets SignatureImageField
        /// </summary>
        [DataMember(Name="SignatureImageField", EmitDefaultValue=true)]
        public string SignatureImageField { get; set; }

        /// <summary>
        /// Gets or Sets SignatureImageIncludeBorderField
        /// </summary>
        [DataMember(Name="SignatureImageIncludeBorderField", EmitDefaultValue=true)]
        public bool SignatureImageIncludeBorderField { get; set; }

        /// <summary>
        /// Gets or Sets SignatureImageIncludeReasonField
        /// </summary>
        [DataMember(Name="SignatureImageIncludeReasonField", EmitDefaultValue=true)]
        public bool SignatureImageIncludeReasonField { get; set; }

        /// <summary>
        /// Gets or Sets SignatureImageIncludeSignedByField
        /// </summary>
        [DataMember(Name="SignatureImageIncludeSignedByField", EmitDefaultValue=true)]
        public bool SignatureImageIncludeSignedByField { get; set; }

        /// <summary>
        /// Gets or Sets SignatureImageIncludeSignedDateField
        /// </summary>
        [DataMember(Name="SignatureImageIncludeSignedDateField", EmitDefaultValue=true)]
        public bool SignatureImageIncludeSignedDateField { get; set; }

        /// <summary>
        /// Gets or Sets SignatureImageTypeField
        /// </summary>
        [DataMember(Name="SignatureImageTypeField", EmitDefaultValue=true)]
        public decimal SignatureImageTypeField { get; set; }

        /// <summary>
        /// Gets or Sets SignaturePageField
        /// </summary>
        [DataMember(Name="SignaturePageField", EmitDefaultValue=true)]
        public decimal SignaturePageField { get; set; }

        /// <summary>
        /// Gets or Sets SignatureWField
        /// </summary>
        [DataMember(Name="SignatureWField", EmitDefaultValue=true)]
        public decimal SignatureWField { get; set; }

        /// <summary>
        /// Gets or Sets SignatureXField
        /// </summary>
        [DataMember(Name="SignatureXField", EmitDefaultValue=true)]
        public decimal SignatureXField { get; set; }

        /// <summary>
        /// Gets or Sets SignatureYField
        /// </summary>
        [DataMember(Name="SignatureYField", EmitDefaultValue=true)]
        public decimal SignatureYField { get; set; }

        /// <summary>
        /// Gets or Sets SignerEmailField
        /// </summary>
        [DataMember(Name="SignerEmailField", EmitDefaultValue=true)]
        public string SignerEmailField { get; set; }

        /// <summary>
        /// Gets or Sets SignerFullNameField
        /// </summary>
        [DataMember(Name="SignerFullNameField", EmitDefaultValue=true)]
        public string SignerFullNameField { get; set; }

        /// <summary>
        /// Gets or Sets SignerIndentificationNumberField
        /// </summary>
        [DataMember(Name="SignerIndentificationNumberField", EmitDefaultValue=true)]
        public string SignerIndentificationNumberField { get; set; }

        /// <summary>
        /// Gets or Sets SignerLocationField
        /// </summary>
        [DataMember(Name="SignerLocationField", EmitDefaultValue=true)]
        public string SignerLocationField { get; set; }

        /// <summary>
        /// Gets or Sets SignerMobileNumberField
        /// </summary>
        [DataMember(Name="SignerMobileNumberField", EmitDefaultValue=true)]
        public string SignerMobileNumberField { get; set; }

        /// <summary>
        /// Gets or Sets SignerReasonField
        /// </summary>
        [DataMember(Name="SignerReasonField", EmitDefaultValue=true)]
        public string SignerReasonField { get; set; }

        /// <summary>
        /// Gets or Sets SignerTrustOriginField
        /// </summary>
        [DataMember(Name="SignerTrustOriginField", EmitDefaultValue=true)]
        public string SignerTrustOriginField { get; set; }

        /// <summary>
        /// Gets or Sets SignerTrustReferenceField
        /// </summary>
        [DataMember(Name="SignerTrustReferenceField", EmitDefaultValue=true)]
        public string SignerTrustReferenceField { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MultipleSignersSigningCeremonyRequestSignerListField {\n");
            sb.Append("  SignatureHField: ").Append(SignatureHField).Append("\n");
            sb.Append("  SignatureImageField: ").Append(SignatureImageField).Append("\n");
            sb.Append("  SignatureImageIncludeBorderField: ").Append(SignatureImageIncludeBorderField).Append("\n");
            sb.Append("  SignatureImageIncludeReasonField: ").Append(SignatureImageIncludeReasonField).Append("\n");
            sb.Append("  SignatureImageIncludeSignedByField: ").Append(SignatureImageIncludeSignedByField).Append("\n");
            sb.Append("  SignatureImageIncludeSignedDateField: ").Append(SignatureImageIncludeSignedDateField).Append("\n");
            sb.Append("  SignatureImageTypeField: ").Append(SignatureImageTypeField).Append("\n");
            sb.Append("  SignaturePageField: ").Append(SignaturePageField).Append("\n");
            sb.Append("  SignatureWField: ").Append(SignatureWField).Append("\n");
            sb.Append("  SignatureXField: ").Append(SignatureXField).Append("\n");
            sb.Append("  SignatureYField: ").Append(SignatureYField).Append("\n");
            sb.Append("  SignerEmailField: ").Append(SignerEmailField).Append("\n");
            sb.Append("  SignerFullNameField: ").Append(SignerFullNameField).Append("\n");
            sb.Append("  SignerIndentificationNumberField: ").Append(SignerIndentificationNumberField).Append("\n");
            sb.Append("  SignerLocationField: ").Append(SignerLocationField).Append("\n");
            sb.Append("  SignerMobileNumberField: ").Append(SignerMobileNumberField).Append("\n");
            sb.Append("  SignerReasonField: ").Append(SignerReasonField).Append("\n");
            sb.Append("  SignerTrustOriginField: ").Append(SignerTrustOriginField).Append("\n");
            sb.Append("  SignerTrustReferenceField: ").Append(SignerTrustReferenceField).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MultipleSignersSigningCeremonyRequestSignerListField);
        }

        /// <summary>
        /// Returns true if MultipleSignersSigningCeremonyRequestSignerListField instances are equal
        /// </summary>
        /// <param name="input">Instance of MultipleSignersSigningCeremonyRequestSignerListField to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MultipleSignersSigningCeremonyRequestSignerListField input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SignatureHField == input.SignatureHField ||
                    (this.SignatureHField != null &&
                    this.SignatureHField.Equals(input.SignatureHField))
                ) && 
                (
                    this.SignatureImageField == input.SignatureImageField ||
                    (this.SignatureImageField != null &&
                    this.SignatureImageField.Equals(input.SignatureImageField))
                ) && 
                (
                    this.SignatureImageIncludeBorderField == input.SignatureImageIncludeBorderField ||
                    (this.SignatureImageIncludeBorderField != null &&
                    this.SignatureImageIncludeBorderField.Equals(input.SignatureImageIncludeBorderField))
                ) && 
                (
                    this.SignatureImageIncludeReasonField == input.SignatureImageIncludeReasonField ||
                    (this.SignatureImageIncludeReasonField != null &&
                    this.SignatureImageIncludeReasonField.Equals(input.SignatureImageIncludeReasonField))
                ) && 
                (
                    this.SignatureImageIncludeSignedByField == input.SignatureImageIncludeSignedByField ||
                    (this.SignatureImageIncludeSignedByField != null &&
                    this.SignatureImageIncludeSignedByField.Equals(input.SignatureImageIncludeSignedByField))
                ) && 
                (
                    this.SignatureImageIncludeSignedDateField == input.SignatureImageIncludeSignedDateField ||
                    (this.SignatureImageIncludeSignedDateField != null &&
                    this.SignatureImageIncludeSignedDateField.Equals(input.SignatureImageIncludeSignedDateField))
                ) && 
                (
                    this.SignatureImageTypeField == input.SignatureImageTypeField ||
                    (this.SignatureImageTypeField != null &&
                    this.SignatureImageTypeField.Equals(input.SignatureImageTypeField))
                ) && 
                (
                    this.SignaturePageField == input.SignaturePageField ||
                    (this.SignaturePageField != null &&
                    this.SignaturePageField.Equals(input.SignaturePageField))
                ) && 
                (
                    this.SignatureWField == input.SignatureWField ||
                    (this.SignatureWField != null &&
                    this.SignatureWField.Equals(input.SignatureWField))
                ) && 
                (
                    this.SignatureXField == input.SignatureXField ||
                    (this.SignatureXField != null &&
                    this.SignatureXField.Equals(input.SignatureXField))
                ) && 
                (
                    this.SignatureYField == input.SignatureYField ||
                    (this.SignatureYField != null &&
                    this.SignatureYField.Equals(input.SignatureYField))
                ) && 
                (
                    this.SignerEmailField == input.SignerEmailField ||
                    (this.SignerEmailField != null &&
                    this.SignerEmailField.Equals(input.SignerEmailField))
                ) && 
                (
                    this.SignerFullNameField == input.SignerFullNameField ||
                    (this.SignerFullNameField != null &&
                    this.SignerFullNameField.Equals(input.SignerFullNameField))
                ) && 
                (
                    this.SignerIndentificationNumberField == input.SignerIndentificationNumberField ||
                    (this.SignerIndentificationNumberField != null &&
                    this.SignerIndentificationNumberField.Equals(input.SignerIndentificationNumberField))
                ) && 
                (
                    this.SignerLocationField == input.SignerLocationField ||
                    (this.SignerLocationField != null &&
                    this.SignerLocationField.Equals(input.SignerLocationField))
                ) && 
                (
                    this.SignerMobileNumberField == input.SignerMobileNumberField ||
                    (this.SignerMobileNumberField != null &&
                    this.SignerMobileNumberField.Equals(input.SignerMobileNumberField))
                ) && 
                (
                    this.SignerReasonField == input.SignerReasonField ||
                    (this.SignerReasonField != null &&
                    this.SignerReasonField.Equals(input.SignerReasonField))
                ) && 
                (
                    this.SignerTrustOriginField == input.SignerTrustOriginField ||
                    (this.SignerTrustOriginField != null &&
                    this.SignerTrustOriginField.Equals(input.SignerTrustOriginField))
                ) && 
                (
                    this.SignerTrustReferenceField == input.SignerTrustReferenceField ||
                    (this.SignerTrustReferenceField != null &&
                    this.SignerTrustReferenceField.Equals(input.SignerTrustReferenceField))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SignatureHField != null)
                    hashCode = hashCode * 59 + this.SignatureHField.GetHashCode();
                if (this.SignatureImageField != null)
                    hashCode = hashCode * 59 + this.SignatureImageField.GetHashCode();
                if (this.SignatureImageIncludeBorderField != null)
                    hashCode = hashCode * 59 + this.SignatureImageIncludeBorderField.GetHashCode();
                if (this.SignatureImageIncludeReasonField != null)
                    hashCode = hashCode * 59 + this.SignatureImageIncludeReasonField.GetHashCode();
                if (this.SignatureImageIncludeSignedByField != null)
                    hashCode = hashCode * 59 + this.SignatureImageIncludeSignedByField.GetHashCode();
                if (this.SignatureImageIncludeSignedDateField != null)
                    hashCode = hashCode * 59 + this.SignatureImageIncludeSignedDateField.GetHashCode();
                if (this.SignatureImageTypeField != null)
                    hashCode = hashCode * 59 + this.SignatureImageTypeField.GetHashCode();
                if (this.SignaturePageField != null)
                    hashCode = hashCode * 59 + this.SignaturePageField.GetHashCode();
                if (this.SignatureWField != null)
                    hashCode = hashCode * 59 + this.SignatureWField.GetHashCode();
                if (this.SignatureXField != null)
                    hashCode = hashCode * 59 + this.SignatureXField.GetHashCode();
                if (this.SignatureYField != null)
                    hashCode = hashCode * 59 + this.SignatureYField.GetHashCode();
                if (this.SignerEmailField != null)
                    hashCode = hashCode * 59 + this.SignerEmailField.GetHashCode();
                if (this.SignerFullNameField != null)
                    hashCode = hashCode * 59 + this.SignerFullNameField.GetHashCode();
                if (this.SignerIndentificationNumberField != null)
                    hashCode = hashCode * 59 + this.SignerIndentificationNumberField.GetHashCode();
                if (this.SignerLocationField != null)
                    hashCode = hashCode * 59 + this.SignerLocationField.GetHashCode();
                if (this.SignerMobileNumberField != null)
                    hashCode = hashCode * 59 + this.SignerMobileNumberField.GetHashCode();
                if (this.SignerReasonField != null)
                    hashCode = hashCode * 59 + this.SignerReasonField.GetHashCode();
                if (this.SignerTrustOriginField != null)
                    hashCode = hashCode * 59 + this.SignerTrustOriginField.GetHashCode();
                if (this.SignerTrustReferenceField != null)
                    hashCode = hashCode * 59 + this.SignerTrustReferenceField.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {

            // SignatureImageField (string) minLength
            if(this.SignatureImageField != null && this.SignatureImageField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignatureImageField, length must be greater than 1.", new [] { "SignatureImageField" });
            }
 

            // SignerEmailField (string) minLength
            if(this.SignerEmailField != null && this.SignerEmailField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerEmailField, length must be greater than 1.", new [] { "SignerEmailField" });
            }
 

            // SignerFullNameField (string) minLength
            if(this.SignerFullNameField != null && this.SignerFullNameField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerFullNameField, length must be greater than 1.", new [] { "SignerFullNameField" });
            }
 

            // SignerIndentificationNumberField (string) minLength
            if(this.SignerIndentificationNumberField != null && this.SignerIndentificationNumberField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerIndentificationNumberField, length must be greater than 1.", new [] { "SignerIndentificationNumberField" });
            }
 

            // SignerLocationField (string) minLength
            if(this.SignerLocationField != null && this.SignerLocationField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerLocationField, length must be greater than 1.", new [] { "SignerLocationField" });
            }
 

            // SignerMobileNumberField (string) minLength
            if(this.SignerMobileNumberField != null && this.SignerMobileNumberField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerMobileNumberField, length must be greater than 1.", new [] { "SignerMobileNumberField" });
            }
 

            // SignerReasonField (string) minLength
            if(this.SignerReasonField != null && this.SignerReasonField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerReasonField, length must be greater than 1.", new [] { "SignerReasonField" });
            }
 

            // SignerTrustOriginField (string) minLength
            if(this.SignerTrustOriginField != null && this.SignerTrustOriginField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerTrustOriginField, length must be greater than 1.", new [] { "SignerTrustOriginField" });
            }
 

            // SignerTrustReferenceField (string) minLength
            if(this.SignerTrustReferenceField != null && this.SignerTrustReferenceField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerTrustReferenceField, length must be greater than 1.", new [] { "SignerTrustReferenceField" });
            }
 
            yield break;
        }
    }

}
