/*
 * WorkFlow API
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SigniFlow.Connect.Client.OpenAPIDateConverter;

namespace SigniFlow.Connect.Model
{
    /// <summary>
    /// #### The request sent to start the signing process of a document.
    /// </summary>
    [DataContract]
    public partial class SigningCeremonyV2Request :  IEquatable<SigningCeremonyV2Request>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SigningCeremonyV2Request" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SigningCeremonyV2Request() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SigningCeremonyV2Request" /> class.
        /// </summary>
        /// <param name="checkboxFieldsListField">The list of checkbox fields. This is array is only required if you add checkboxes to your document..</param>
        /// <param name="docField">Base64 encoded string. (required).</param>
        /// <param name="docNameField">Document name. (required).</param>
        /// <param name="initialFieldsListField">The list of initial fields. This is array is only required if you add initial fields to your document..</param>
        /// <param name="loginPasswordField">User password. (required).</param>
        /// <param name="loginUserNameField">User&#39;s username. (required).</param>
        /// <param name="signatureHField">Signature field height. (required).</param>
        /// <param name="signatureImageField">Signature field image. (required).</param>
        /// <param name="signatureImageIncludeBorderField">Include signature border. (required).</param>
        /// <param name="signatureImageIncludeReasonField">Include signature reason. (required).</param>
        /// <param name="signatureImageIncludeSignedByField">Include signature signed by information. (required).</param>
        /// <param name="signatureImageIncludeSignedDateField">Include signature date. (required).</param>
        /// <param name="signatureImageTypeField">Signature image type. (required).</param>
        /// <param name="signaturePageField">The page on which the signature is on. (required).</param>
        /// <param name="signatureWField">Signature field width. (required).</param>
        /// <param name="signatureXField">Signature field x-coordinates. (required).</param>
        /// <param name="signatureYField">Signature field y-coordinates. (required).</param>
        /// <param name="signerEmailField">The signer&#39;s email. (required).</param>
        /// <param name="signerFullNameField">The signer&#39;s full name. (required).</param>
        /// <param name="signerIdentificationNumberField">The signer&#39;s ID number..</param>
        /// <param name="signerLocationField">The signer&#39;s GPS location. (required).</param>
        /// <param name="signerMobileNumberField">The signer&#39;s mobile number. (required).</param>
        /// <param name="signerReasonField">The signer&#39;s reason for signing..</param>
        /// <param name="signerTrustOriginField">This field is used to define the source of the Audit keep by the user calling the Signing Ceremony. (required).</param>
        /// <param name="signerTrustReferenceField">A unique identifier that links back to an audit stored by the user calling the Signing Ceremony. (required).</param>
        /// <param name="textFieldsListField">The list of text fields. This is array is only required if you add text fields to your document..</param>
        public SigningCeremonyV2Request(List<SigningCeremonyV2RequestCheckboxFieldsListField> checkboxFieldsListField = default(List<SigningCeremonyV2RequestCheckboxFieldsListField>), string docField = default(string), string docNameField = default(string), List<SigningCeremonyV2RequestInitialFieldsListField> initialFieldsListField = default(List<SigningCeremonyV2RequestInitialFieldsListField>), string loginPasswordField = default(string), string loginUserNameField = default(string), decimal signatureHField = default(decimal), string signatureImageField = default(string), bool signatureImageIncludeBorderField = default(bool), bool signatureImageIncludeReasonField = default(bool), bool signatureImageIncludeSignedByField = default(bool), bool signatureImageIncludeSignedDateField = default(bool), decimal signatureImageTypeField = default(decimal), decimal signaturePageField = default(decimal), decimal signatureWField = default(decimal), decimal signatureXField = default(decimal), decimal signatureYField = default(decimal), string signerEmailField = default(string), string signerFullNameField = default(string), string signerIdentificationNumberField = default(string), string signerLocationField = default(string), string signerMobileNumberField = default(string), string signerReasonField = default(string), string signerTrustOriginField = default(string), string signerTrustReferenceField = default(string), List<SigningCeremonyV2RequestTextFieldsListField> textFieldsListField = default(List<SigningCeremonyV2RequestTextFieldsListField>))
        {
            // to ensure "docField" is required (not null)
            if (docField == null)
            {
                throw new InvalidDataException("docField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.DocField = docField;
            }

            // to ensure "docNameField" is required (not null)
            if (docNameField == null)
            {
                throw new InvalidDataException("docNameField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.DocNameField = docNameField;
            }

            // to ensure "loginPasswordField" is required (not null)
            if (loginPasswordField == null)
            {
                throw new InvalidDataException("loginPasswordField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.LoginPasswordField = loginPasswordField;
            }

            // to ensure "loginUserNameField" is required (not null)
            if (loginUserNameField == null)
            {
                throw new InvalidDataException("loginUserNameField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.LoginUserNameField = loginUserNameField;
            }

            // to ensure "signatureHField" is required (not null)
            if (signatureHField == null)
            {
                throw new InvalidDataException("signatureHField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignatureHField = signatureHField;
            }

            // to ensure "signatureImageField" is required (not null)
            if (signatureImageField == null)
            {
                throw new InvalidDataException("signatureImageField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignatureImageField = signatureImageField;
            }

            // to ensure "signatureImageIncludeBorderField" is required (not null)
            if (signatureImageIncludeBorderField == null)
            {
                throw new InvalidDataException("signatureImageIncludeBorderField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignatureImageIncludeBorderField = signatureImageIncludeBorderField;
            }

            // to ensure "signatureImageIncludeReasonField" is required (not null)
            if (signatureImageIncludeReasonField == null)
            {
                throw new InvalidDataException("signatureImageIncludeReasonField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignatureImageIncludeReasonField = signatureImageIncludeReasonField;
            }

            // to ensure "signatureImageIncludeSignedByField" is required (not null)
            if (signatureImageIncludeSignedByField == null)
            {
                throw new InvalidDataException("signatureImageIncludeSignedByField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignatureImageIncludeSignedByField = signatureImageIncludeSignedByField;
            }

            // to ensure "signatureImageIncludeSignedDateField" is required (not null)
            if (signatureImageIncludeSignedDateField == null)
            {
                throw new InvalidDataException("signatureImageIncludeSignedDateField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignatureImageIncludeSignedDateField = signatureImageIncludeSignedDateField;
            }

            // to ensure "signatureImageTypeField" is required (not null)
            if (signatureImageTypeField == null)
            {
                throw new InvalidDataException("signatureImageTypeField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignatureImageTypeField = signatureImageTypeField;
            }

            // to ensure "signaturePageField" is required (not null)
            if (signaturePageField == null)
            {
                throw new InvalidDataException("signaturePageField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignaturePageField = signaturePageField;
            }

            // to ensure "signatureWField" is required (not null)
            if (signatureWField == null)
            {
                throw new InvalidDataException("signatureWField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignatureWField = signatureWField;
            }

            // to ensure "signatureXField" is required (not null)
            if (signatureXField == null)
            {
                throw new InvalidDataException("signatureXField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignatureXField = signatureXField;
            }

            // to ensure "signatureYField" is required (not null)
            if (signatureYField == null)
            {
                throw new InvalidDataException("signatureYField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignatureYField = signatureYField;
            }

            // to ensure "signerEmailField" is required (not null)
            if (signerEmailField == null)
            {
                throw new InvalidDataException("signerEmailField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignerEmailField = signerEmailField;
            }

            // to ensure "signerFullNameField" is required (not null)
            if (signerFullNameField == null)
            {
                throw new InvalidDataException("signerFullNameField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignerFullNameField = signerFullNameField;
            }

            // to ensure "signerLocationField" is required (not null)
            if (signerLocationField == null)
            {
                throw new InvalidDataException("signerLocationField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignerLocationField = signerLocationField;
            }

            // to ensure "signerMobileNumberField" is required (not null)
            if (signerMobileNumberField == null)
            {
                throw new InvalidDataException("signerMobileNumberField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignerMobileNumberField = signerMobileNumberField;
            }

            // to ensure "signerTrustOriginField" is required (not null)
            if (signerTrustOriginField == null)
            {
                throw new InvalidDataException("signerTrustOriginField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignerTrustOriginField = signerTrustOriginField;
            }

            // to ensure "signerTrustReferenceField" is required (not null)
            if (signerTrustReferenceField == null)
            {
                throw new InvalidDataException("signerTrustReferenceField is a required property for SigningCeremonyV2Request and cannot be null");
            }
            else
            {
                this.SignerTrustReferenceField = signerTrustReferenceField;
            }

            this.CheckboxFieldsListField = checkboxFieldsListField;
            this.InitialFieldsListField = initialFieldsListField;
            this.SignerIdentificationNumberField = signerIdentificationNumberField;
            this.SignerReasonField = signerReasonField;
            this.TextFieldsListField = textFieldsListField;
        }

        /// <summary>
        /// The list of checkbox fields. This is array is only required if you add checkboxes to your document.
        /// </summary>
        /// <value>The list of checkbox fields. This is array is only required if you add checkboxes to your document.</value>
        [DataMember(Name="CheckboxFieldsListField", EmitDefaultValue=false)]        public List<SigningCeremonyV2RequestCheckboxFieldsListField> CheckboxFieldsListField { get; set; }

        /// <summary>
        /// Base64 encoded string.
        /// </summary>
        /// <value>Base64 encoded string.</value>
        [DataMember(Name="DocField", EmitDefaultValue=true)]        public string DocField { get; set; }

        /// <summary>
        /// Document name.
        /// </summary>
        /// <value>Document name.</value>
        [DataMember(Name="DocNameField", EmitDefaultValue=true)]        public string DocNameField { get; set; }

        /// <summary>
        /// The list of initial fields. This is array is only required if you add initial fields to your document.
        /// </summary>
        /// <value>The list of initial fields. This is array is only required if you add initial fields to your document.</value>
        [DataMember(Name="InitialFieldsListField", EmitDefaultValue=false)]        public List<SigningCeremonyV2RequestInitialFieldsListField> InitialFieldsListField { get; set; }

        /// <summary>
        /// User password.
        /// </summary>
        /// <value>User password.</value>
        [DataMember(Name="LoginPasswordField", EmitDefaultValue=true)]        public string LoginPasswordField { get; set; }

        /// <summary>
        /// User&#39;s username.
        /// </summary>
        /// <value>User&#39;s username.</value>
        [DataMember(Name="LoginUserNameField", EmitDefaultValue=true)]        public string LoginUserNameField { get; set; }

        /// <summary>
        /// Signature field height.
        /// </summary>
        /// <value>Signature field height.</value>
        [DataMember(Name="SignatureHField", EmitDefaultValue=true)]        public decimal SignatureHField { get; set; }

        /// <summary>
        /// Signature field image.
        /// </summary>
        /// <value>Signature field image.</value>
        [DataMember(Name="SignatureImageField", EmitDefaultValue=true)]        public string SignatureImageField { get; set; }

        /// <summary>
        /// Include signature border.
        /// </summary>
        /// <value>Include signature border.</value>
        [DataMember(Name="SignatureImageIncludeBorderField", EmitDefaultValue=true)]        public bool SignatureImageIncludeBorderField { get; set; }

        /// <summary>
        /// Include signature reason.
        /// </summary>
        /// <value>Include signature reason.</value>
        [DataMember(Name="SignatureImageIncludeReasonField", EmitDefaultValue=true)]        public bool SignatureImageIncludeReasonField { get; set; }

        /// <summary>
        /// Include signature signed by information.
        /// </summary>
        /// <value>Include signature signed by information.</value>
        [DataMember(Name="SignatureImageIncludeSignedByField", EmitDefaultValue=true)]        public bool SignatureImageIncludeSignedByField { get; set; }

        /// <summary>
        /// Include signature date.
        /// </summary>
        /// <value>Include signature date.</value>
        [DataMember(Name="SignatureImageIncludeSignedDateField", EmitDefaultValue=true)]        public bool SignatureImageIncludeSignedDateField { get; set; }

        /// <summary>
        /// Signature image type.
        /// </summary>
        /// <value>Signature image type.</value>
        [DataMember(Name="SignatureImageTypeField", EmitDefaultValue=true)]        public decimal SignatureImageTypeField { get; set; }

        /// <summary>
        /// The page on which the signature is on.
        /// </summary>
        /// <value>The page on which the signature is on.</value>
        [DataMember(Name="SignaturePageField", EmitDefaultValue=true)]        public decimal SignaturePageField { get; set; }

        /// <summary>
        /// Signature field width.
        /// </summary>
        /// <value>Signature field width.</value>
        [DataMember(Name="SignatureWField", EmitDefaultValue=true)]        public decimal SignatureWField { get; set; }

        /// <summary>
        /// Signature field x-coordinates.
        /// </summary>
        /// <value>Signature field x-coordinates.</value>
        [DataMember(Name="SignatureXField", EmitDefaultValue=true)]        public decimal SignatureXField { get; set; }

        /// <summary>
        /// Signature field y-coordinates.
        /// </summary>
        /// <value>Signature field y-coordinates.</value>
        [DataMember(Name="SignatureYField", EmitDefaultValue=true)]        public decimal SignatureYField { get; set; }

        /// <summary>
        /// The signer&#39;s email.
        /// </summary>
        /// <value>The signer&#39;s email.</value>
        [DataMember(Name="SignerEmailField", EmitDefaultValue=true)]        public string SignerEmailField { get; set; }

        /// <summary>
        /// The signer&#39;s full name.
        /// </summary>
        /// <value>The signer&#39;s full name.</value>
        [DataMember(Name="SignerFullNameField", EmitDefaultValue=true)]        public string SignerFullNameField { get; set; }

        /// <summary>
        /// The signer&#39;s ID number.
        /// </summary>
        /// <value>The signer&#39;s ID number.</value>
        [DataMember(Name="SignerIdentificationNumberField", EmitDefaultValue=false)]        public string SignerIdentificationNumberField { get; set; }

        /// <summary>
        /// The signer&#39;s GPS location.
        /// </summary>
        /// <value>The signer&#39;s GPS location.</value>
        [DataMember(Name="SignerLocationField", EmitDefaultValue=true)]        public string SignerLocationField { get; set; }

        /// <summary>
        /// The signer&#39;s mobile number.
        /// </summary>
        /// <value>The signer&#39;s mobile number.</value>
        [DataMember(Name="SignerMobileNumberField", EmitDefaultValue=true)]        public string SignerMobileNumberField { get; set; }

        /// <summary>
        /// The signer&#39;s reason for signing.
        /// </summary>
        /// <value>The signer&#39;s reason for signing.</value>
        [DataMember(Name="SignerReasonField", EmitDefaultValue=false)]        public string SignerReasonField { get; set; }

        /// <summary>
        /// This field is used to define the source of the Audit keep by the user calling the Signing Ceremony.
        /// </summary>
        /// <value>This field is used to define the source of the Audit keep by the user calling the Signing Ceremony.</value>
        [DataMember(Name="SignerTrustOriginField", EmitDefaultValue=true)]        public string SignerTrustOriginField { get; set; }

        /// <summary>
        /// A unique identifier that links back to an audit stored by the user calling the Signing Ceremony.
        /// </summary>
        /// <value>A unique identifier that links back to an audit stored by the user calling the Signing Ceremony.</value>
        [DataMember(Name="SignerTrustReferenceField", EmitDefaultValue=true)]        public string SignerTrustReferenceField { get; set; }

        /// <summary>
        /// The list of text fields. This is array is only required if you add text fields to your document.
        /// </summary>
        /// <value>The list of text fields. This is array is only required if you add text fields to your document.</value>
        [DataMember(Name="TextFieldsListField", EmitDefaultValue=false)]        public List<SigningCeremonyV2RequestTextFieldsListField> TextFieldsListField { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SigningCeremonyV2Request {\n");
            sb.Append("  CheckboxFieldsListField: ").Append(CheckboxFieldsListField).Append("\n");
            sb.Append("  DocField: ").Append(DocField).Append("\n");
            sb.Append("  DocNameField: ").Append(DocNameField).Append("\n");
            sb.Append("  InitialFieldsListField: ").Append(InitialFieldsListField).Append("\n");
            sb.Append("  LoginPasswordField: ").Append(LoginPasswordField).Append("\n");
            sb.Append("  LoginUserNameField: ").Append(LoginUserNameField).Append("\n");
            sb.Append("  SignatureHField: ").Append(SignatureHField).Append("\n");
            sb.Append("  SignatureImageField: ").Append(SignatureImageField).Append("\n");
            sb.Append("  SignatureImageIncludeBorderField: ").Append(SignatureImageIncludeBorderField).Append("\n");
            sb.Append("  SignatureImageIncludeReasonField: ").Append(SignatureImageIncludeReasonField).Append("\n");
            sb.Append("  SignatureImageIncludeSignedByField: ").Append(SignatureImageIncludeSignedByField).Append("\n");
            sb.Append("  SignatureImageIncludeSignedDateField: ").Append(SignatureImageIncludeSignedDateField).Append("\n");
            sb.Append("  SignatureImageTypeField: ").Append(SignatureImageTypeField).Append("\n");
            sb.Append("  SignaturePageField: ").Append(SignaturePageField).Append("\n");
            sb.Append("  SignatureWField: ").Append(SignatureWField).Append("\n");
            sb.Append("  SignatureXField: ").Append(SignatureXField).Append("\n");
            sb.Append("  SignatureYField: ").Append(SignatureYField).Append("\n");
            sb.Append("  SignerEmailField: ").Append(SignerEmailField).Append("\n");
            sb.Append("  SignerFullNameField: ").Append(SignerFullNameField).Append("\n");
            sb.Append("  SignerIdentificationNumberField: ").Append(SignerIdentificationNumberField).Append("\n");
            sb.Append("  SignerLocationField: ").Append(SignerLocationField).Append("\n");
            sb.Append("  SignerMobileNumberField: ").Append(SignerMobileNumberField).Append("\n");
            sb.Append("  SignerReasonField: ").Append(SignerReasonField).Append("\n");
            sb.Append("  SignerTrustOriginField: ").Append(SignerTrustOriginField).Append("\n");
            sb.Append("  SignerTrustReferenceField: ").Append(SignerTrustReferenceField).Append("\n");
            sb.Append("  TextFieldsListField: ").Append(TextFieldsListField).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SigningCeremonyV2Request);
        }

        /// <summary>
        /// Returns true if SigningCeremonyV2Request instances are equal
        /// </summary>
        /// <param name="input">Instance of SigningCeremonyV2Request to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SigningCeremonyV2Request input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CheckboxFieldsListField == input.CheckboxFieldsListField ||
                    this.CheckboxFieldsListField != null &&
                    input.CheckboxFieldsListField != null &&
                    this.CheckboxFieldsListField.SequenceEqual(input.CheckboxFieldsListField)
                ) && 
                (
                    this.DocField == input.DocField ||
                    (this.DocField != null &&
                    this.DocField.Equals(input.DocField))
                ) && 
                (
                    this.DocNameField == input.DocNameField ||
                    (this.DocNameField != null &&
                    this.DocNameField.Equals(input.DocNameField))
                ) && 
                (
                    this.InitialFieldsListField == input.InitialFieldsListField ||
                    this.InitialFieldsListField != null &&
                    input.InitialFieldsListField != null &&
                    this.InitialFieldsListField.SequenceEqual(input.InitialFieldsListField)
                ) && 
                (
                    this.LoginPasswordField == input.LoginPasswordField ||
                    (this.LoginPasswordField != null &&
                    this.LoginPasswordField.Equals(input.LoginPasswordField))
                ) && 
                (
                    this.LoginUserNameField == input.LoginUserNameField ||
                    (this.LoginUserNameField != null &&
                    this.LoginUserNameField.Equals(input.LoginUserNameField))
                ) && 
                (
                    this.SignatureHField == input.SignatureHField ||
                    (this.SignatureHField != null &&
                    this.SignatureHField.Equals(input.SignatureHField))
                ) && 
                (
                    this.SignatureImageField == input.SignatureImageField ||
                    (this.SignatureImageField != null &&
                    this.SignatureImageField.Equals(input.SignatureImageField))
                ) && 
                (
                    this.SignatureImageIncludeBorderField == input.SignatureImageIncludeBorderField ||
                    (this.SignatureImageIncludeBorderField != null &&
                    this.SignatureImageIncludeBorderField.Equals(input.SignatureImageIncludeBorderField))
                ) && 
                (
                    this.SignatureImageIncludeReasonField == input.SignatureImageIncludeReasonField ||
                    (this.SignatureImageIncludeReasonField != null &&
                    this.SignatureImageIncludeReasonField.Equals(input.SignatureImageIncludeReasonField))
                ) && 
                (
                    this.SignatureImageIncludeSignedByField == input.SignatureImageIncludeSignedByField ||
                    (this.SignatureImageIncludeSignedByField != null &&
                    this.SignatureImageIncludeSignedByField.Equals(input.SignatureImageIncludeSignedByField))
                ) && 
                (
                    this.SignatureImageIncludeSignedDateField == input.SignatureImageIncludeSignedDateField ||
                    (this.SignatureImageIncludeSignedDateField != null &&
                    this.SignatureImageIncludeSignedDateField.Equals(input.SignatureImageIncludeSignedDateField))
                ) && 
                (
                    this.SignatureImageTypeField == input.SignatureImageTypeField ||
                    (this.SignatureImageTypeField != null &&
                    this.SignatureImageTypeField.Equals(input.SignatureImageTypeField))
                ) && 
                (
                    this.SignaturePageField == input.SignaturePageField ||
                    (this.SignaturePageField != null &&
                    this.SignaturePageField.Equals(input.SignaturePageField))
                ) && 
                (
                    this.SignatureWField == input.SignatureWField ||
                    (this.SignatureWField != null &&
                    this.SignatureWField.Equals(input.SignatureWField))
                ) && 
                (
                    this.SignatureXField == input.SignatureXField ||
                    (this.SignatureXField != null &&
                    this.SignatureXField.Equals(input.SignatureXField))
                ) && 
                (
                    this.SignatureYField == input.SignatureYField ||
                    (this.SignatureYField != null &&
                    this.SignatureYField.Equals(input.SignatureYField))
                ) && 
                (
                    this.SignerEmailField == input.SignerEmailField ||
                    (this.SignerEmailField != null &&
                    this.SignerEmailField.Equals(input.SignerEmailField))
                ) && 
                (
                    this.SignerFullNameField == input.SignerFullNameField ||
                    (this.SignerFullNameField != null &&
                    this.SignerFullNameField.Equals(input.SignerFullNameField))
                ) && 
                (
                    this.SignerIdentificationNumberField == input.SignerIdentificationNumberField ||
                    (this.SignerIdentificationNumberField != null &&
                    this.SignerIdentificationNumberField.Equals(input.SignerIdentificationNumberField))
                ) && 
                (
                    this.SignerLocationField == input.SignerLocationField ||
                    (this.SignerLocationField != null &&
                    this.SignerLocationField.Equals(input.SignerLocationField))
                ) && 
                (
                    this.SignerMobileNumberField == input.SignerMobileNumberField ||
                    (this.SignerMobileNumberField != null &&
                    this.SignerMobileNumberField.Equals(input.SignerMobileNumberField))
                ) && 
                (
                    this.SignerReasonField == input.SignerReasonField ||
                    (this.SignerReasonField != null &&
                    this.SignerReasonField.Equals(input.SignerReasonField))
                ) && 
                (
                    this.SignerTrustOriginField == input.SignerTrustOriginField ||
                    (this.SignerTrustOriginField != null &&
                    this.SignerTrustOriginField.Equals(input.SignerTrustOriginField))
                ) && 
                (
                    this.SignerTrustReferenceField == input.SignerTrustReferenceField ||
                    (this.SignerTrustReferenceField != null &&
                    this.SignerTrustReferenceField.Equals(input.SignerTrustReferenceField))
                ) && 
                (
                    this.TextFieldsListField == input.TextFieldsListField ||
                    this.TextFieldsListField != null &&
                    input.TextFieldsListField != null &&
                    this.TextFieldsListField.SequenceEqual(input.TextFieldsListField)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CheckboxFieldsListField != null)
                    hashCode = hashCode * 59 + this.CheckboxFieldsListField.GetHashCode();
                if (this.DocField != null)
                    hashCode = hashCode * 59 + this.DocField.GetHashCode();
                if (this.DocNameField != null)
                    hashCode = hashCode * 59 + this.DocNameField.GetHashCode();
                if (this.InitialFieldsListField != null)
                    hashCode = hashCode * 59 + this.InitialFieldsListField.GetHashCode();
                if (this.LoginPasswordField != null)
                    hashCode = hashCode * 59 + this.LoginPasswordField.GetHashCode();
                if (this.LoginUserNameField != null)
                    hashCode = hashCode * 59 + this.LoginUserNameField.GetHashCode();
                if (this.SignatureHField != null)
                    hashCode = hashCode * 59 + this.SignatureHField.GetHashCode();
                if (this.SignatureImageField != null)
                    hashCode = hashCode * 59 + this.SignatureImageField.GetHashCode();
                if (this.SignatureImageIncludeBorderField != null)
                    hashCode = hashCode * 59 + this.SignatureImageIncludeBorderField.GetHashCode();
                if (this.SignatureImageIncludeReasonField != null)
                    hashCode = hashCode * 59 + this.SignatureImageIncludeReasonField.GetHashCode();
                if (this.SignatureImageIncludeSignedByField != null)
                    hashCode = hashCode * 59 + this.SignatureImageIncludeSignedByField.GetHashCode();
                if (this.SignatureImageIncludeSignedDateField != null)
                    hashCode = hashCode * 59 + this.SignatureImageIncludeSignedDateField.GetHashCode();
                if (this.SignatureImageTypeField != null)
                    hashCode = hashCode * 59 + this.SignatureImageTypeField.GetHashCode();
                if (this.SignaturePageField != null)
                    hashCode = hashCode * 59 + this.SignaturePageField.GetHashCode();
                if (this.SignatureWField != null)
                    hashCode = hashCode * 59 + this.SignatureWField.GetHashCode();
                if (this.SignatureXField != null)
                    hashCode = hashCode * 59 + this.SignatureXField.GetHashCode();
                if (this.SignatureYField != null)
                    hashCode = hashCode * 59 + this.SignatureYField.GetHashCode();
                if (this.SignerEmailField != null)
                    hashCode = hashCode * 59 + this.SignerEmailField.GetHashCode();
                if (this.SignerFullNameField != null)
                    hashCode = hashCode * 59 + this.SignerFullNameField.GetHashCode();
                if (this.SignerIdentificationNumberField != null)
                    hashCode = hashCode * 59 + this.SignerIdentificationNumberField.GetHashCode();
                if (this.SignerLocationField != null)
                    hashCode = hashCode * 59 + this.SignerLocationField.GetHashCode();
                if (this.SignerMobileNumberField != null)
                    hashCode = hashCode * 59 + this.SignerMobileNumberField.GetHashCode();
                if (this.SignerReasonField != null)
                    hashCode = hashCode * 59 + this.SignerReasonField.GetHashCode();
                if (this.SignerTrustOriginField != null)
                    hashCode = hashCode * 59 + this.SignerTrustOriginField.GetHashCode();
                if (this.SignerTrustReferenceField != null)
                    hashCode = hashCode * 59 + this.SignerTrustReferenceField.GetHashCode();
                if (this.TextFieldsListField != null)
                    hashCode = hashCode * 59 + this.TextFieldsListField.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {

 

            // DocField (string) minLength
            if(this.DocField != null && this.DocField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DocField, length must be greater than 1.", new [] { "DocField" });
            }
 

            // DocNameField (string) minLength
            if(this.DocNameField != null && this.DocNameField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DocNameField, length must be greater than 1.", new [] { "DocNameField" });
            }
 

 

            // LoginPasswordField (string) minLength
            if(this.LoginPasswordField != null && this.LoginPasswordField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LoginPasswordField, length must be greater than 1.", new [] { "LoginPasswordField" });
            }
 

            // LoginUserNameField (string) minLength
            if(this.LoginUserNameField != null && this.LoginUserNameField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LoginUserNameField, length must be greater than 1.", new [] { "LoginUserNameField" });
            }
 

            // SignatureImageField (string) minLength
            if(this.SignatureImageField != null && this.SignatureImageField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignatureImageField, length must be greater than 1.", new [] { "SignatureImageField" });
            }
 

            // SignerEmailField (string) minLength
            if(this.SignerEmailField != null && this.SignerEmailField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerEmailField, length must be greater than 1.", new [] { "SignerEmailField" });
            }
 

            // SignerFullNameField (string) minLength
            if(this.SignerFullNameField != null && this.SignerFullNameField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerFullNameField, length must be greater than 1.", new [] { "SignerFullNameField" });
            }
 

            // SignerIdentificationNumberField (string) minLength
            if(this.SignerIdentificationNumberField != null && this.SignerIdentificationNumberField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerIdentificationNumberField, length must be greater than 1.", new [] { "SignerIdentificationNumberField" });
            }
 

            // SignerLocationField (string) minLength
            if(this.SignerLocationField != null && this.SignerLocationField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerLocationField, length must be greater than 1.", new [] { "SignerLocationField" });
            }
 

            // SignerMobileNumberField (string) minLength
            if(this.SignerMobileNumberField != null && this.SignerMobileNumberField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerMobileNumberField, length must be greater than 1.", new [] { "SignerMobileNumberField" });
            }
 

            // SignerReasonField (string) minLength
            if(this.SignerReasonField != null && this.SignerReasonField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerReasonField, length must be greater than 1.", new [] { "SignerReasonField" });
            }
 

            // SignerTrustOriginField (string) minLength
            if(this.SignerTrustOriginField != null && this.SignerTrustOriginField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerTrustOriginField, length must be greater than 1.", new [] { "SignerTrustOriginField" });
            }
 

            // SignerTrustReferenceField (string) minLength
            if(this.SignerTrustReferenceField != null && this.SignerTrustReferenceField.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SignerTrustReferenceField, length must be greater than 1.", new [] { "SignerTrustReferenceField" });
            }
 

 
            yield break;
        }
    }

}
