/*
 * WorkFlow API
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test
{
    /// <summary>
    ///  Class for testing AddWorkflowStepV2Request
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddWorkflowStepV2RequestTests
    {
        // TODO uncomment below to declare an instance variable for AddWorkflowStepV2Request
        //private AddWorkflowStepV2Request instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AddWorkflowStepV2Request
            //instance = new AddWorkflowStepV2Request();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AddWorkflowStepV2Request
        /// </summary>
        [Test]
        public void AddWorkflowStepV2RequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" AddWorkflowStepV2Request
            //Assert.IsInstanceOf(typeof(AddWorkflowStepV2Request), instance);
        }


        /// <summary>
        /// Test the property 'ActionField'
        /// </summary>
        [Test]
        public void ActionFieldTest()
        {
            // TODO unit test for the property 'ActionField'
        }
        /// <summary>
        /// Test the property 'CellField'
        /// </summary>
        [Test]
        public void CellFieldTest()
        {
            // TODO unit test for the property 'CellField'
        }
        /// <summary>
        /// Test the property 'DocIDField'
        /// </summary>
        [Test]
        public void DocIDFieldTest()
        {
            // TODO unit test for the property 'DocIDField'
        }
        /// <summary>
        /// Test the property 'EmailField'
        /// </summary>
        [Test]
        public void EmailFieldTest()
        {
            // TODO unit test for the property 'EmailField'
        }
        /// <summary>
        /// Test the property 'FirstNameField'
        /// </summary>
        [Test]
        public void FirstNameFieldTest()
        {
            // TODO unit test for the property 'FirstNameField'
        }
        /// <summary>
        /// Test the property 'LanguageCodeField'
        /// </summary>
        [Test]
        public void LanguageCodeFieldTest()
        {
            // TODO unit test for the property 'LanguageCodeField'
        }
        /// <summary>
        /// Test the property 'LastNameField'
        /// </summary>
        [Test]
        public void LastNameFieldTest()
        {
            // TODO unit test for the property 'LastNameField'
        }
        /// <summary>
        /// Test the property 'ProxyAllowedField'
        /// </summary>
        [Test]
        public void ProxyAllowedFieldTest()
        {
            // TODO unit test for the property 'ProxyAllowedField'
        }
        /// <summary>
        /// Test the property 'TokenField'
        /// </summary>
        [Test]
        public void TokenFieldTest()
        {
            // TODO unit test for the property 'TokenField'
        }

    }

}
