/*
 * SigniFlow API
 *
 * API for adding watermarks to documents
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.CertifyCeremonyAPI.Model;
using SigniFlow.CertifyCeremonyAPI.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.CertifyCeremonyAPI.Test.Model
{
    /// <summary>
    ///  Class for testing AddWatermarkByFileRequestTextRGBColorField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddWatermarkByFileRequestTextRGBColorFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddWatermarkByFileRequestTextRGBColorField
        //private AddWatermarkByFileRequestTextRGBColorField instance;

        public AddWatermarkByFileRequestTextRGBColorFieldTests()
        {
            // TODO uncomment below to create an instance of AddWatermarkByFileRequestTextRGBColorField
            //instance = new AddWatermarkByFileRequestTextRGBColorField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddWatermarkByFileRequestTextRGBColorField
        /// </summary>
        [Fact]
        public void AddWatermarkByFileRequestTextRGBColorFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddWatermarkByFileRequestTextRGBColorField
            //Assert.IsType<AddWatermarkByFileRequestTextRGBColorField>(instance);
        }

        /// <summary>
        /// Test the property 'BlueField'
        /// </summary>
        [Fact]
        public void BlueFieldTest()
        {
            // TODO unit test for the property 'BlueField'
        }

        /// <summary>
        /// Test the property 'GreenField'
        /// </summary>
        [Fact]
        public void GreenFieldTest()
        {
            // TODO unit test for the property 'GreenField'
        }

        /// <summary>
        /// Test the property 'RedField'
        /// </summary>
        [Fact]
        public void RedFieldTest()
        {
            // TODO unit test for the property 'RedField'
        }
    }
}
