/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test.Model
{
    /// <summary>
    ///  Class for testing ApplyPrepperTemplateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApplyPrepperTemplateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApplyPrepperTemplateRequest
        //private ApplyPrepperTemplateRequest instance;

        public ApplyPrepperTemplateRequestTests()
        {
            // TODO uncomment below to create an instance of ApplyPrepperTemplateRequest
            //instance = new ApplyPrepperTemplateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApplyPrepperTemplateRequest
        /// </summary>
        [Fact]
        public void ApplyPrepperTemplateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApplyPrepperTemplateRequest
            //Assert.IsType<ApplyPrepperTemplateRequest>(instance);
        }


        /// <summary>
        /// Test the property 'DocIDField'
        /// </summary>
        [Fact]
        public void DocIDFieldTest()
        {
            // TODO unit test for the property 'DocIDField'
        }
        /// <summary>
        /// Test the property 'PrepperTemplateIDField'
        /// </summary>
        [Fact]
        public void PrepperTemplateIDFieldTest()
        {
            // TODO unit test for the property 'PrepperTemplateIDField'
        }
        /// <summary>
        /// Test the property 'TokenField'
        /// </summary>
        [Fact]
        public void TokenFieldTest()
        {
            // TODO unit test for the property 'TokenField'
        }

    }

}
