/*
 * Certify Ceremony API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test.Model
{
    /// <summary>
    ///  Class for testing CertifyCeremonyWithTokenRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CertifyCeremonyWithTokenRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CertifyCeremonyWithTokenRequest
        //private CertifyCeremonyWithTokenRequest instance;

        public CertifyCeremonyWithTokenRequestTests()
        {
            // TODO uncomment below to create an instance of CertifyCeremonyWithTokenRequest
            //instance = new CertifyCeremonyWithTokenRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CertifyCeremonyWithTokenRequest
        /// </summary>
        [Fact]
        public void CertifyCeremonyWithTokenRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CertifyCeremonyWithTokenRequest
            //Assert.IsType<CertifyCeremonyWithTokenRequest>(instance);
        }

        /// <summary>
        /// Test the property 'DocField'
        /// </summary>
        [Fact]
        public void DocFieldTest()
        {
            // TODO unit test for the property 'DocField'
        }

        /// <summary>
        /// Test the property 'DocNameField'
        /// </summary>
        [Fact]
        public void DocNameFieldTest()
        {
            // TODO unit test for the property 'DocNameField'
        }

        /// <summary>
        /// Test the property 'SignerEmailField'
        /// </summary>
        [Fact]
        public void SignerEmailFieldTest()
        {
            // TODO unit test for the property 'SignerEmailField'
        }

        /// <summary>
        /// Test the property 'SignerFullNameField'
        /// </summary>
        [Fact]
        public void SignerFullNameFieldTest()
        {
            // TODO unit test for the property 'SignerFullNameField'
        }

        /// <summary>
        /// Test the property 'SignerIdentificationNumberField'
        /// </summary>
        [Fact]
        public void SignerIdentificationNumberFieldTest()
        {
            // TODO unit test for the property 'SignerIdentificationNumberField'
        }

        /// <summary>
        /// Test the property 'SignerLocationField'
        /// </summary>
        [Fact]
        public void SignerLocationFieldTest()
        {
            // TODO unit test for the property 'SignerLocationField'
        }

        /// <summary>
        /// Test the property 'SignerMobileNumberField'
        /// </summary>
        [Fact]
        public void SignerMobileNumberFieldTest()
        {
            // TODO unit test for the property 'SignerMobileNumberField'
        }

        /// <summary>
        /// Test the property 'SignerReasonField'
        /// </summary>
        [Fact]
        public void SignerReasonFieldTest()
        {
            // TODO unit test for the property 'SignerReasonField'
        }

        /// <summary>
        /// Test the property 'SignerTrustOriginField'
        /// </summary>
        [Fact]
        public void SignerTrustOriginFieldTest()
        {
            // TODO unit test for the property 'SignerTrustOriginField'
        }

        /// <summary>
        /// Test the property 'SignerTrustReferenceField'
        /// </summary>
        [Fact]
        public void SignerTrustReferenceFieldTest()
        {
            // TODO unit test for the property 'SignerTrustReferenceField'
        }

        /// <summary>
        /// Test the property 'TokenField'
        /// </summary>
        [Fact]
        public void TokenFieldTest()
        {
            // TODO unit test for the property 'TokenField'
        }
    }
}
