/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test.Model
{
    /// <summary>
    ///  Class for testing DownloadPortfolioRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DownloadPortfolioRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DownloadPortfolioRequest
        //private DownloadPortfolioRequest instance;

        public DownloadPortfolioRequestTests()
        {
            // TODO uncomment below to create an instance of DownloadPortfolioRequest
            //instance = new DownloadPortfolioRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DownloadPortfolioRequest
        /// </summary>
        [Fact]
        public void DownloadPortfolioRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DownloadPortfolioRequest
            //Assert.IsType<DownloadPortfolioRequest>(instance);
        }


        /// <summary>
        /// Test the property 'PortfolioIDField'
        /// </summary>
        [Fact]
        public void PortfolioIDFieldTest()
        {
            // TODO unit test for the property 'PortfolioIDField'
        }
        /// <summary>
        /// Test the property 'TokenField'
        /// </summary>
        [Fact]
        public void TokenFieldTest()
        {
            // TODO unit test for the property 'TokenField'
        }

    }

}
