/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test
{
    /// <summary>
    ///  Class for testing FullWorkflowRequestGroupStepFieldGroupMembersField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FullWorkflowRequestGroupStepFieldGroupMembersFieldTests
    {
        // TODO uncomment below to declare an instance variable for FullWorkflowRequestGroupStepFieldGroupMembersField
        //private FullWorkflowRequestGroupStepFieldGroupMembersField instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FullWorkflowRequestGroupStepFieldGroupMembersField
            //instance = new FullWorkflowRequestGroupStepFieldGroupMembersField();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FullWorkflowRequestGroupStepFieldGroupMembersField
        /// </summary>
        [Test]
        public void FullWorkflowRequestGroupStepFieldGroupMembersFieldInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" FullWorkflowRequestGroupStepFieldGroupMembersField
            //Assert.IsInstanceOf(typeof(FullWorkflowRequestGroupStepFieldGroupMembersField), instance);
        }


        /// <summary>
        /// Test the property 'LanguageCodeField'
        /// </summary>
        [Test]
        public void LanguageCodeFieldTest()
        {
            // TODO unit test for the property 'LanguageCodeField'
        }
        /// <summary>
        /// Test the property 'UserEmailField'
        /// </summary>
        [Test]
        public void UserEmailFieldTest()
        {
            // TODO unit test for the property 'UserEmailField'
        }
        /// <summary>
        /// Test the property 'UserFullNameField'
        /// </summary>
        [Test]
        public void UserFullNameFieldTest()
        {
            // TODO unit test for the property 'UserFullNameField'
        }
        /// <summary>
        /// Test the property 'UserMobileNumberField'
        /// </summary>
        [Test]
        public void UserMobileNumberFieldTest()
        {
            // TODO unit test for the property 'UserMobileNumberField'
        }

    }

}
