/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test.Model
{
    /// <summary>
    ///  Class for testing FullWorkflowRequestGroupStepField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FullWorkflowRequestGroupStepFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FullWorkflowRequestGroupStepField
        //private FullWorkflowRequestGroupStepField instance;

        public FullWorkflowRequestGroupStepFieldTests()
        {
            // TODO uncomment below to create an instance of FullWorkflowRequestGroupStepField
            //instance = new FullWorkflowRequestGroupStepField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FullWorkflowRequestGroupStepField
        /// </summary>
        [Fact]
        public void FullWorkflowRequestGroupStepFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" FullWorkflowRequestGroupStepField
            //Assert.IsType<FullWorkflowRequestGroupStepField>(instance);
        }


        /// <summary>
        /// Test the property 'GroupMembersField'
        /// </summary>
        [Fact]
        public void GroupMembersFieldTest()
        {
            // TODO unit test for the property 'GroupMembersField'
        }
        /// <summary>
        /// Test the property 'GroupNameField'
        /// </summary>
        [Fact]
        public void GroupNameFieldTest()
        {
            // TODO unit test for the property 'GroupNameField'
        }
        /// <summary>
        /// Test the property 'RequiredNumberOfSignaturesField'
        /// </summary>
        [Fact]
        public void RequiredNumberOfSignaturesFieldTest()
        {
            // TODO unit test for the property 'RequiredNumberOfSignaturesField'
        }

    }

}
