/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test.Model
{
    /// <summary>
    ///  Class for testing GetDocLinkResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetDocLinkResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetDocLinkResponse
        //private GetDocLinkResponse instance;

        public GetDocLinkResponseTests()
        {
            // TODO uncomment below to create an instance of GetDocLinkResponse
            //instance = new GetDocLinkResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetDocLinkResponse
        /// </summary>
        [Fact]
        public void GetDocLinkResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetDocLinkResponse
            //Assert.IsType<GetDocLinkResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

    }

}
