/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test.Model
{
    /// <summary>
    ///  Class for testing GetDocumentAuditResponseActivityField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetDocumentAuditResponseActivityFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetDocumentAuditResponseActivityField
        //private GetDocumentAuditResponseActivityField instance;

        public GetDocumentAuditResponseActivityFieldTests()
        {
            // TODO uncomment below to create an instance of GetDocumentAuditResponseActivityField
            //instance = new GetDocumentAuditResponseActivityField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetDocumentAuditResponseActivityField
        /// </summary>
        [Fact]
        public void GetDocumentAuditResponseActivityFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetDocumentAuditResponseActivityField
            //Assert.IsType<GetDocumentAuditResponseActivityField>(instance);
        }


        /// <summary>
        /// Test the property 'ActionOrderField'
        /// </summary>
        [Fact]
        public void ActionOrderFieldTest()
        {
            // TODO unit test for the property 'ActionOrderField'
        }
        /// <summary>
        /// Test the property 'AdditionalField'
        /// </summary>
        [Fact]
        public void AdditionalFieldTest()
        {
            // TODO unit test for the property 'AdditionalField'
        }
        /// <summary>
        /// Test the property 'DocIDField'
        /// </summary>
        [Fact]
        public void DocIDFieldTest()
        {
            // TODO unit test for the property 'DocIDField'
        }
        /// <summary>
        /// Test the property 'EmailField'
        /// </summary>
        [Fact]
        public void EmailFieldTest()
        {
            // TODO unit test for the property 'EmailField'
        }
        /// <summary>
        /// Test the property 'EventDateField'
        /// </summary>
        [Fact]
        public void EventDateFieldTest()
        {
            // TODO unit test for the property 'EventDateField'
        }
        /// <summary>
        /// Test the property 'EventField'
        /// </summary>
        [Fact]
        public void EventFieldTest()
        {
            // TODO unit test for the property 'EventField'
        }
        /// <summary>
        /// Test the property 'EventStatusField'
        /// </summary>
        [Fact]
        public void EventStatusFieldTest()
        {
            // TODO unit test for the property 'EventStatusField'
        }
        /// <summary>
        /// Test the property 'LocationField'
        /// </summary>
        [Fact]
        public void LocationFieldTest()
        {
            // TODO unit test for the property 'LocationField'
        }
        /// <summary>
        /// Test the property 'OrderDateField'
        /// </summary>
        [Fact]
        public void OrderDateFieldTest()
        {
            // TODO unit test for the property 'OrderDateField'
        }
        /// <summary>
        /// Test the property 'PageField'
        /// </summary>
        [Fact]
        public void PageFieldTest()
        {
            // TODO unit test for the property 'PageField'
        }
        /// <summary>
        /// Test the property 'UserFullNameField'
        /// </summary>
        [Fact]
        public void UserFullNameFieldTest()
        {
            // TODO unit test for the property 'UserFullNameField'
        }

    }

}
