/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test.Model
{
    /// <summary>
    ///  Class for testing GetDocumentPrepperLinkRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetDocumentPrepperLinkRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetDocumentPrepperLinkRequest
        //private GetDocumentPrepperLinkRequest instance;

        public GetDocumentPrepperLinkRequestTests()
        {
            // TODO uncomment below to create an instance of GetDocumentPrepperLinkRequest
            //instance = new GetDocumentPrepperLinkRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetDocumentPrepperLinkRequest
        /// </summary>
        [Fact]
        public void GetDocumentPrepperLinkRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetDocumentPrepperLinkRequest
            //Assert.IsType<GetDocumentPrepperLinkRequest>(instance);
        }


        /// <summary>
        /// Test the property 'DocIDField'
        /// </summary>
        [Fact]
        public void DocIDFieldTest()
        {
            // TODO unit test for the property 'DocIDField'
        }
        /// <summary>
        /// Test the property 'EmailSettingField'
        /// </summary>
        [Fact]
        public void EmailSettingFieldTest()
        {
            // TODO unit test for the property 'EmailSettingField'
        }
        /// <summary>
        /// Test the property 'ReturnURLField'
        /// </summary>
        [Fact]
        public void ReturnURLFieldTest()
        {
            // TODO unit test for the property 'ReturnURLField'
        }
        /// <summary>
        /// Test the property 'TokenField'
        /// </summary>
        [Fact]
        public void TokenFieldTest()
        {
            // TODO unit test for the property 'TokenField'
        }

    }

}
