/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test
{
    /// <summary>
    ///  Class for testing LoginRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoginRequestTests
    {
        // TODO uncomment below to declare an instance variable for LoginRequest
        //private LoginRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoginRequest
            //instance = new LoginRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoginRequest
        /// </summary>
        [Test]
        public void LoginRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" LoginRequest
            //Assert.IsInstanceOf(typeof(LoginRequest), instance);
        }


        /// <summary>
        /// Test the property 'UserNameField'
        /// </summary>
        [Test]
        public void UserNameFieldTest()
        {
            // TODO unit test for the property 'UserNameField'
        }
        /// <summary>
        /// Test the property 'PasswordField'
        /// </summary>
        [Test]
        public void PasswordFieldTest()
        {
            // TODO unit test for the property 'PasswordField'
        }

    }

}
