/*
 * WorkFlow API
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test
{
    /// <summary>
    ///  Class for testing LogoutResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LogoutResponseTests
    {
        // TODO uncomment below to declare an instance variable for LogoutResponse
        //private LogoutResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LogoutResponse
            //instance = new LogoutResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LogoutResponse
        /// </summary>
        [Test]
        public void LogoutResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" LogoutResponse
            //Assert.IsInstanceOf(typeof(LogoutResponse), instance);
        }


        /// <summary>
        /// Test the property 'ResultField'
        /// </summary>
        [Test]
        public void ResultFieldTest()
        {
            // TODO unit test for the property 'ResultField'
        }
        /// <summary>
        /// Test the property 'TokenField'
        /// </summary>
        [Test]
        public void TokenFieldTest()
        {
            // TODO unit test for the property 'TokenField'
        }

    }

}
