/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test.Model
{
    /// <summary>
    ///  Class for testing ProxyAllowedField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProxyAllowedFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProxyAllowedField
        //private ProxyAllowedField instance;

        public ProxyAllowedFieldTests()
        {
            // TODO uncomment below to create an instance of ProxyAllowedField
            //instance = new ProxyAllowedField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProxyAllowedField
        /// </summary>
        [Fact]
        public void ProxyAllowedFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProxyAllowedField
            //Assert.IsType<ProxyAllowedField>(instance);
        }



    }

}
