/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test.Model
{
    /// <summary>
    ///  Class for testing SharePortfolioRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SharePortfolioRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SharePortfolioRequest
        //private SharePortfolioRequest instance;

        public SharePortfolioRequestTests()
        {
            // TODO uncomment below to create an instance of SharePortfolioRequest
            //instance = new SharePortfolioRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SharePortfolioRequest
        /// </summary>
        [Fact]
        public void SharePortfolioRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SharePortfolioRequest
            //Assert.IsType<SharePortfolioRequest>(instance);
        }


        /// <summary>
        /// Test the property 'AccessLevelField'
        /// </summary>
        [Fact]
        public void AccessLevelFieldTest()
        {
            // TODO unit test for the property 'AccessLevelField'
        }
        /// <summary>
        /// Test the property 'PortfolioIDField'
        /// </summary>
        [Fact]
        public void PortfolioIDFieldTest()
        {
            // TODO unit test for the property 'PortfolioIDField'
        }
        /// <summary>
        /// Test the property 'ShareOptionField'
        /// </summary>
        [Fact]
        public void ShareOptionFieldTest()
        {
            // TODO unit test for the property 'ShareOptionField'
        }
        /// <summary>
        /// Test the property 'TokenField'
        /// </summary>
        [Fact]
        public void TokenFieldTest()
        {
            // TODO unit test for the property 'TokenField'
        }
        /// <summary>
        /// Test the property 'UniqueIDField'
        /// </summary>
        [Fact]
        public void UniqueIDFieldTest()
        {
            // TODO unit test for the property 'UniqueIDField'
        }

    }

}
