/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test.Model
{
    /// <summary>
    ///  Class for testing SigningCeremonyV2RequestInitialFieldsListField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SigningCeremonyV2RequestInitialFieldsListFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SigningCeremonyV2RequestInitialFieldsListField
        //private SigningCeremonyV2RequestInitialFieldsListField instance;

        public SigningCeremonyV2RequestInitialFieldsListFieldTests()
        {
            // TODO uncomment below to create an instance of SigningCeremonyV2RequestInitialFieldsListField
            //instance = new SigningCeremonyV2RequestInitialFieldsListField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SigningCeremonyV2RequestInitialFieldsListField
        /// </summary>
        [Fact]
        public void SigningCeremonyV2RequestInitialFieldsListFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" SigningCeremonyV2RequestInitialFieldsListField
            //Assert.IsType<SigningCeremonyV2RequestInitialFieldsListField>(instance);
        }


        /// <summary>
        /// Test the property 'InitialHField'
        /// </summary>
        [Fact]
        public void InitialHFieldTest()
        {
            // TODO unit test for the property 'InitialHField'
        }
        /// <summary>
        /// Test the property 'InitialImageField'
        /// </summary>
        [Fact]
        public void InitialImageFieldTest()
        {
            // TODO unit test for the property 'InitialImageField'
        }
        /// <summary>
        /// Test the property 'InitialImageTypeField'
        /// </summary>
        [Fact]
        public void InitialImageTypeFieldTest()
        {
            // TODO unit test for the property 'InitialImageTypeField'
        }
        /// <summary>
        /// Test the property 'InitialPageField'
        /// </summary>
        [Fact]
        public void InitialPageFieldTest()
        {
            // TODO unit test for the property 'InitialPageField'
        }
        /// <summary>
        /// Test the property 'InitialWField'
        /// </summary>
        [Fact]
        public void InitialWFieldTest()
        {
            // TODO unit test for the property 'InitialWField'
        }
        /// <summary>
        /// Test the property 'InitialXField'
        /// </summary>
        [Fact]
        public void InitialXFieldTest()
        {
            // TODO unit test for the property 'InitialXField'
        }
        /// <summary>
        /// Test the property 'InitialYField'
        /// </summary>
        [Fact]
        public void InitialYFieldTest()
        {
            // TODO unit test for the property 'InitialYField'
        }

    }

}
