/*
 * WorkFlow API
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test
{
    /// <summary>
    ///  Class for testing SigningCeremonyV2RequestInitialFieldsListField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SigningCeremonyV2RequestInitialFieldsListFieldTests
    {
        // TODO uncomment below to declare an instance variable for SigningCeremonyV2RequestInitialFieldsListField
        //private SigningCeremonyV2RequestInitialFieldsListField instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SigningCeremonyV2RequestInitialFieldsListField
            //instance = new SigningCeremonyV2RequestInitialFieldsListField();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SigningCeremonyV2RequestInitialFieldsListField
        /// </summary>
        [Test]
        public void SigningCeremonyV2RequestInitialFieldsListFieldInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SigningCeremonyV2RequestInitialFieldsListField
            //Assert.IsInstanceOf(typeof(SigningCeremonyV2RequestInitialFieldsListField), instance);
        }


        /// <summary>
        /// Test the property 'InitialHField'
        /// </summary>
        [Test]
        public void InitialHFieldTest()
        {
            // TODO unit test for the property 'InitialHField'
        }
        /// <summary>
        /// Test the property 'InitialImageField'
        /// </summary>
        [Test]
        public void InitialImageFieldTest()
        {
            // TODO unit test for the property 'InitialImageField'
        }
        /// <summary>
        /// Test the property 'InitialImageTypeField'
        /// </summary>
        [Test]
        public void InitialImageTypeFieldTest()
        {
            // TODO unit test for the property 'InitialImageTypeField'
        }
        /// <summary>
        /// Test the property 'InitialPageField'
        /// </summary>
        [Test]
        public void InitialPageFieldTest()
        {
            // TODO unit test for the property 'InitialPageField'
        }
        /// <summary>
        /// Test the property 'InitialWField'
        /// </summary>
        [Test]
        public void InitialWFieldTest()
        {
            // TODO unit test for the property 'InitialWField'
        }
        /// <summary>
        /// Test the property 'InitialXField'
        /// </summary>
        [Test]
        public void InitialXFieldTest()
        {
            // TODO unit test for the property 'InitialXField'
        }
        /// <summary>
        /// Test the property 'InitialYField'
        /// </summary>
        [Test]
        public void InitialYFieldTest()
        {
            // TODO unit test for the property 'InitialYField'
        }

    }

}
