/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test.Model
{
    /// <summary>
    ///  Class for testing SigningCeremonyV2RequestCheckboxFieldsListField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SigningCeremonyV2RequestCheckboxFieldsListFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SigningCeremonyV2RequestCheckboxFieldsListField
        //private SigningCeremonyV2RequestCheckboxFieldsListField instance;

        public SigningCeremonyV2RequestCheckboxFieldsListFieldTests()
        {
            // TODO uncomment below to create an instance of SigningCeremonyV2RequestCheckboxFieldsListField
            //instance = new SigningCeremonyV2RequestCheckboxFieldsListField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SigningCeremonyV2RequestCheckboxFieldsListField
        /// </summary>
        [Fact]
        public void SigningCeremonyV2RequestCheckboxFieldsListFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" SigningCeremonyV2RequestCheckboxFieldsListField
            //Assert.IsType<SigningCeremonyV2RequestCheckboxFieldsListField>(instance);
        }


        /// <summary>
        /// Test the property 'CheckboxHField'
        /// </summary>
        [Fact]
        public void CheckboxHFieldTest()
        {
            // TODO unit test for the property 'CheckboxHField'
        }
        /// <summary>
        /// Test the property 'CheckboxPageField'
        /// </summary>
        [Fact]
        public void CheckboxPageFieldTest()
        {
            // TODO unit test for the property 'CheckboxPageField'
        }
        /// <summary>
        /// Test the property 'CheckboxWField'
        /// </summary>
        [Fact]
        public void CheckboxWFieldTest()
        {
            // TODO unit test for the property 'CheckboxWField'
        }
        /// <summary>
        /// Test the property 'CheckboxXField'
        /// </summary>
        [Fact]
        public void CheckboxXFieldTest()
        {
            // TODO unit test for the property 'CheckboxXField'
        }
        /// <summary>
        /// Test the property 'CheckboxYField'
        /// </summary>
        [Fact]
        public void CheckboxYFieldTest()
        {
            // TODO unit test for the property 'CheckboxYField'
        }
        /// <summary>
        /// Test the property 'IsCheckedField'
        /// </summary>
        [Fact]
        public void IsCheckedFieldTest()
        {
            // TODO unit test for the property 'IsCheckedField'
        }

    }

}
