/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test.Model
{
    /// <summary>
    ///  Class for testing TokenValidateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenValidateResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokenValidateResponse
        //private TokenValidateResponse instance;

        public TokenValidateResponseTests()
        {
            // TODO uncomment below to create an instance of TokenValidateResponse
            //instance = new TokenValidateResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenValidateResponse
        /// </summary>
        [Fact]
        public void TokenValidateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokenValidateResponse
            //Assert.IsType<TokenValidateResponse>(instance);
        }


        /// <summary>
        /// Test the property 'ResultField'
        /// </summary>
        [Fact]
        public void ResultFieldTest()
        {
            // TODO unit test for the property 'ResultField'
        }
        /// <summary>
        /// Test the property 'TokenField'
        /// </summary>
        [Fact]
        public void TokenFieldTest()
        {
            // TODO unit test for the property 'TokenField'
        }

    }

}
