/*
 * SigniFlow OpenAPI Spec v1
 *
 * ## SigniFlow API used to automate esignature workflow creation and management. 
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@signiflow.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SigniFlow.Connect.Api;
using SigniFlow.Connect.Model;
using SigniFlow.Connect.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SigniFlow.Connect.Test.Model
{
    /// <summary>
    ///  Class for testing WorkflowSignRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkflowSignRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkflowSignRequest
        //private WorkflowSignRequest instance;

        public WorkflowSignRequestTests()
        {
            // TODO uncomment below to create an instance of WorkflowSignRequest
            //instance = new WorkflowSignRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkflowSignRequest
        /// </summary>
        [Fact]
        public void WorkflowSignRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkflowSignRequest
            //Assert.IsType<WorkflowSignRequest>(instance);
        }


        /// <summary>
        /// Test the property 'DocIDField'
        /// </summary>
        [Fact]
        public void DocIDFieldTest()
        {
            // TODO unit test for the property 'DocIDField'
        }
        /// <summary>
        /// Test the property 'LatitudeField'
        /// </summary>
        [Fact]
        public void LatitudeFieldTest()
        {
            // TODO unit test for the property 'LatitudeField'
        }
        /// <summary>
        /// Test the property 'LoginPasswordField'
        /// </summary>
        [Fact]
        public void LoginPasswordFieldTest()
        {
            // TODO unit test for the property 'LoginPasswordField'
        }
        /// <summary>
        /// Test the property 'LoginUserNameField'
        /// </summary>
        [Fact]
        public void LoginUserNameFieldTest()
        {
            // TODO unit test for the property 'LoginUserNameField'
        }
        /// <summary>
        /// Test the property 'LongitudeField'
        /// </summary>
        [Fact]
        public void LongitudeFieldTest()
        {
            // TODO unit test for the property 'LongitudeField'
        }
        /// <summary>
        /// Test the property 'SignReasonField'
        /// </summary>
        [Fact]
        public void SignReasonFieldTest()
        {
            // TODO unit test for the property 'SignReasonField'
        }
        /// <summary>
        /// Test the property 'TimeZoneOffsetField'
        /// </summary>
        [Fact]
        public void TimeZoneOffsetFieldTest()
        {
            // TODO unit test for the property 'TimeZoneOffsetField'
        }
        /// <summary>
        /// Test the property 'TokenField'
        /// </summary>
        [Fact]
        public void TokenFieldTest()
        {
            // TODO unit test for the property 'TokenField'
        }

    }

}
