openapi: 3.0.0
info:
  title: Certify Ceremony API
  version: 1.0.0
paths:
  /CertifyCeremonyWithToken:
    post:
      summary: Certify a ceremony
      operationId: CertifyCeremonyWithToken
      tags:
        - Ceremony
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CertifyCeremonyWithTokenRequest'
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CertifyCeremonyWithTokenResponse'
        '400':
          description: Bad request
        '500':
          description: Internal server error
components:
  schemas:
    CertifyCeremonyWithTokenRequest:
      type: object
      required:
        - DocField
        - DocNameField
        - SignerEmailField
        - SignerFullNameField
        - SignerIdentificationNumberField
        - SignerLocationField
        - SignerMobileNumberField
        - SignerReasonField
        - SignerTrustOriginField
        - SignerTrustReferenceField
        - TokenField
      properties:
        DocField:
          type: string
          description: Document content
        DocNameField:
          type: string
          description: Document name
        SignerEmailField:
          type: string
          description: Signer's email
        SignerFullNameField:
          type: string
          description: Signer's full name
        SignerIdentificationNumberField:
          type: string
          description: Signer's identification number
        SignerLocationField:
          type: string
          description: Signer's location
        SignerMobileNumberField:
          type: string
          description: Signer's mobile number
        SignerReasonField:
          type: string
          description: Reason for signing
        SignerTrustOriginField:
          type: string
          description: Trust origin of the signer
        SignerTrustReferenceField:
          type: string
          description: Trust reference of the signer
        TokenField:
          $ref: '#/components/schemas/TokenField'  # Reference to the existing TokenField class

    TokenField:
      type: object
      required:
        - TokenExpiryField
        - TokenField
      properties:
        TokenExpiryField:
          type: string
          format: date-time
          description: Expiry date of the token
          example: "/Date(928142400000+0200)/"
        TokenField:
          type: string
          description: The user API token

    CertifyCeremonyWithTokenResponse:
      type: object
      properties:
        CeremonyIDField:
          type: integer
          description: Ceremony ID
          example: 2147483647
        ResultField:
          type: string
          description: Result of the ceremony
        SignedDocumentField:
          type: string
          description: Signed document content
